language: java
os: linux
dist: focal
addons:
  apt:
    packages:
      - openjdk-8-jdk
env:
  global:
    - PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin/:$PATH
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
before_install:
  - mvn -v
install:
  - mvn install -DskipTests=true -Pstaging -Dmaven.javadoc.skip=true -B -V
script: mvn --fail-at-end clean verify -Pstaging

